name: root
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.6
  - setuptools=41.2.0
  - wheel=0.33.6
  - docopt=0.6.2
  - nltk=3.4.5
  - pip:
    - opencv-python==3.4.5.20
    - librosa==0.6.3
    - tensorboardx==1.6
