name: root
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.6
  - setuptools=41.2.0
  - wheel=0.33.6
  - numpy=1.16.*
  - docopt=0.6.2
  - nltk=3.4.5
  - pip:
    - git+https://github.com/r9y9/deepvoice3_pytorch@bc90c403e5f3ef7d3dd08621f7a7d2637e7d95dc#egg=deepvoice3_pytorch
    - https://download.pytorch.org/whl/cpu/torchvision-0.4.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl
    - https://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
    - opencv-python==3.4.5.20
    - librosa==0.6.3
    - tensorboardx==1.6
    - nnmnkwii==0.0.19
    - lws==1.2
